name: Checks

on:
  push:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7']
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # prerequisites
        python -m pip install --upgrade pip wheel
        python -m pip install pytest
        # install dependencies
        pip install -e .[all]
        # show installed packages
        pip freeze
    - name: Test with pytest
      run: |
        pytest tests/test_create.py

